### ISSUE TITLE
`test-pdb.exe` is blocked by Cb Defense

### ISSUE THREAD

**Issue by terlar** [rust-lang/lldb#23]
At my work computer we are running Cb Defense, every time I try to install rust it fails to build to to the file [test-pdb.exe](https://github.com/rust-lang-nursery/lldb/blob/fdea743be550ed8d7b61b2c908944cdd1290a6ad/unittests/SymbolFile/PDB/Inputs/test-pdb.exe).

It blocks the file as "Known malware" and won't agree to unpack the source. Anyone else experience something similar and have an idea how to solve it.

**Comment by tromey** [comment]
If you are trying to build Rust from source, you don't really need this submodule -- unless you really want to build lldb.  Is that what you're trying?

Upstream bug: https://bugs.llvm.org/show_bug.cgi?id=35652

**Comment by terlar** [comment]
I get this issue when I try to install (upgrade) rust via homebrew, I am not entirely sure what procedure it does.

```
==> Upgrading rust 
==> Downloading https://homebrew.bintray.com/bottles/rust-1.30.1.mojave.bottle.tar.gz
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/964316235f4a205a567053c93c8190e62d090468c8c957fec5178a7f53486cd2--rust-1.30.1.mojave.bottle.tar.gz
==> Pouring rust-1.30.1.mojave.bottle.tar.gz
cp: /var/folders/kt/8b_27d717w10423xq_v19v28b91d88/T/d20181112-4279-1rnt6j1/rust/./1.30.1/share/rust/rust_src/tools/lldb/unittests/SymbolFile/PDB/Inputs/test-pdb.exe: Operation not permitted
Error: Failure while executing; `cp -pR /var/folders/kt/8b_27d717w10423xq_v19v28b91d88/T/d20181112-4279-1rnt6j1/rust/. /usr/local/Cellar/rust` exited with 1. Here's the output:
cp: /var/folders/kt/8b_27d717w10423xq_v19v28b91d88/T/d20181112-4279-1rnt6j1/rust/./1.30.1/share/rust/rust_src/tools/lldb/unittests/SymbolFile/PDB/Inputs/test-pdb.exe: Operation not permitted

Warning: Bottle installation failed: building from source.
==> Downloading https://static.rust-lang.org/dist/rustc-1.30.1-src.tar.gz
Already downloaded: /Users/user/Library/Caches/Homebrew/downloads/c3dfdef9895d43b3d086cf3be52eddc652877ba63192ab18686360c552c6a917--rustc-1.30.1-src.tar.gz
cp: /private/tmp/d20181112-5189-1wpx92c/rustc-1.30.1-src/./src/tools/lldb/unittests/SymbolFile/PDB/Inputs/test-pdb.exe: Operation not permitted
Error: undefined method `shelljoin' for nil:NilClass
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/exceptions.rb:539:in `initialize'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `new'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:7:in `rewrite_child_error'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:84:in `block (3 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils.rb:402:in `ignore_interrupts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:60:in `block (2 levels) in safe_fork'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:29:in `open'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:29:in `block in safe_fork'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:28:in `safe_fork'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:743:in `build'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:317:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:163:in `upgrade_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:109:in `block in upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:106:in `upgrade_formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/upgrade.rb:84:in `upgrade'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
```

I don't think it is brew specific though since it is blocking this file.

This seems to be the source:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/rust.rb

However I seem to be able to download the file manually and unpack the file, seems it is the actual cp command that fails. I reproduced it as such:
```
$ curl -O https://homebrew.bintray.com/bottles/rust-1.30.1.mojave.bottle.tar.gz
$ tar -zxf rust-1.30.1.mojave.bottle.tar.gz
$ cp rust/1.30.1/share/rust/rust_src/tools/lldb/unittests/SymbolFile/PDB/Inputs/test-pdb.exe .
cp: cannot open 'rust/1.30.1/share/rust/rust_src/tools/lldb/unittests/SymbolFile/PDB/Inputs/test-pdb.exe' for reading: Operation not permitted
```

**Comment by terlar** [comment]
Seems this is the related thread:
https://github.com/Homebrew/homebrew-core/issues/33421

**Comment by tromey** [comment]
I think this is something that should be addressed upstream - it isn't specific to the rust fork of lldb and I am not sure I would want to accept a patch to delete the file, or anything like that.  Workarounds for you would be to disable AV, or to install rust via rustup, which doesn't require source installation.

**Comment by terlar** [comment]
I understand, thank you for the tips, I will probably go for rustup then as I am not able to disable AV on this computer.
